### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'indexOf')

### ISSUE THREAD

**Issue by michelscholte** [hobbyquaker/lgtv2mqtt#18]
I'm getting this error. Is there a solution for it?
Thank you

/usr/lib/node_modules/lgtv2mqtt/index.js:137
        if (res.changed.indexOf('volume') !== -1) {
                        ^

TypeError: Cannot read properties of undefined (reading 'indexOf')
    at Object.bed14b150001 (/usr/lib/node_modules/lgtv2mqtt/index.js:137:25)
    at WebSocketConnection.<anonymous> (/usr/lib/node_modules/lgtv2mqtt/node_modules/lgtv2/index.js:149:48)
    at WebSocketConnection.emit (node:events:513:28)
    at WebSocketConnection.processFrame (/usr/lib/node_modules/lgtv2mqtt/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /usr/lib/node_modules/lgtv2mqtt/node_modules/websocket/lib/WebSocketConnection.js:323:40
    at processTicksAndRejections (node:internal/process/task_queues:78:11)

**Comment by Rybun** [comment]
Hi, I changed the following from the 137 line of file /usr/lib/node_modules/lgtv2mqtt/index.js :

From:

```
        if (res.changed.indexOf('volume') !== -1) {
            mqtt.publish(config.name + '/status/volume', String(res.volume), {retain: true});
        }
        if (res.changed.indexOf('muted') !== -1) {
            mqtt.publish(config.name + '/status/mute', res.muted ? '1' : '0', {retain: true});
        }
    });
```

To:

```
        if (res && res.changed && res.changed.indexOf('volume') !== -1) {
            mqtt.publish(config.name + '/status/volume', String(res.volume), {retain: true});
        }
        if (res && res.changed && res.changed.indexOf('muted') !== -1) {
            mqtt.publish(config.name + '/status/mute', res.muted ? '1' : '0', {retain: true});
        }
    });
```

After that, It seems to work.

**Comment by hobbyquaker** [comment]
Fixed in 1.2.0: newer firmware answers getVolume with a volumeStatus object and no changed array. lgtv2 1.7+ normalizes the payload and all subscription callbacks now guard err/res, so this can no longer crash the process. Thanks @Rybun for the workaround.
